// <auto-generated />
namespace Logs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vasiliystan_62864fe486ad40509a334f32ac79ba87 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_62864fe486ad40509a334f32ac79ba87));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191430194_vasiliy.stan_62864fe486ad40509a334f32ac79ba87"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
