// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Logs.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vasiliystan_6714e9077a3d4050997998650cf8784c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_6714e9077a3d4050997998650cf8784c));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140522109_vasiliy.stan_6714e9077a3d4050997998650cf8784c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
