// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vasiliystan_eaff28a0e72042c1b8ee27cde7ef12e5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_eaff28a0e72042c1b8ee27cde7ef12e5));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140505325_vasiliy.stan_eaff28a0e72042c1b8ee27cde7ef12e5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
