#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Layouts\Base.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Layouts\Base.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Layouts/Base.cshtml")]
    public partial class _Layouts_Base_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Layouts_Base_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n        <title>\r\n");

WriteLiteral("            ");

            
            #line 10 "..\..\Layouts\Base.cshtml"
       Write(RenderSection("pagetitle", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </title>\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Layouts\Base.cshtml"
   Write(Styles.Render("~/Libraries/Components/Preloader/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Layouts\Base.cshtml"
   Write(Styles.Render("~/Themes/startbootstrap-sb-admin-2/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Layouts\Base.cshtml"
   Write(Styles.Render("~/Libraries/Common/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Layouts\Base.cshtml"
   Write(RenderSection("stylesheet", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Layouts\Base.cshtml"
   Write(Scripts.Render("~/Themes/startbootstrap-sb-admin-2/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Layouts\Base.cshtml"
   Write(Scripts.Render("~/Libraries/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Layouts\Base.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Layouts\Base.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Layouts\Base.cshtml"
   Write(RenderSection("headscripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body>\r\n        <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">        \r\n            <div");

WriteLiteral(" id=\"status\"");

WriteLiteral(">&nbsp;</div>\r\n        </div>    \r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Layouts\Base.cshtml"
               Write(Html.ActionLink("Test work with bitcoin network", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 31 "..\..\Layouts\Base.cshtml"
                
            
            #line default
            #line hidden
            
            #line 31 "..\..\Layouts\Base.cshtml"
                 if (User.Identity.IsAuthenticated)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 34 "..\..\Layouts\Base.cshtml"
                   Write(Html.ActionLink("Exit", "Logout", "Accounts", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>                    \r\n");

            
            #line 36 "..\..\Layouts\Base.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Layouts\Base.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 40 "..\..\Layouts\Base.cshtml"
   Write(RenderSection("bodyscripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 41 "..\..\Layouts\Base.cshtml"
   Write(Scripts.Render("~/Libraries/Components/Preloader/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
